name: prod aws deployment

on:
  push:
    branches:
      - test

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run Lint
        run: poetry run make lint

      - name: Run Tests
        run: poetry run make test
